#!/bin/bash -xe

# Cross-compile librealsense2 for Jetson Orin Nano + JetPack 6.2
# Host: x86_64 Ubuntu; Target: aarch64 Ubuntu 22.04 (JetPack 6.2)
#
# Prerequisites on the host:
#   sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
#   Install CUDA cross-compile packages (from developer.download.nvidia.com):
#     cuda-cross-aarch64-12-6  (or the version matching your host CUDA toolkit)
#
# Sysroot setup:
#   The SYSROOT must contain the Jetson's /usr, /lib, /include, etc.
#   Recommended: use NVIDIA SDK Manager to produce a full Jetson rootfs, then
#   point SYSROOT at it.  A minimal sysroot can be bootstrapped with:
#     sudo apt install qemu-user-static debootstrap
#     sudo debootstrap --arch=arm64 jammy /opt/jetson-sysroot \
#         http://ports.ubuntu.com/ubuntu-ports
#   then add JetPack apt repos and install libudev-dev:arm64, libusb-1.0-0-dev:arm64, etc.
#
# Usage:
#   ./jetson_libuvc_crosscompile_installation.sh [Release|Debug]
#
# Override defaults via environment variables before running, e.g.:
#   SYSROOT=/my/rootfs STAGING_DIR=/tmp/deploy ./jetson_libuvc_crosscompile_installation.sh

if [ -z "$1" ]; then
    build_type=Release
else
    build_type=$1
fi

echo "Building $build_type for aarch64 (Jetson Orin Nano / JetPack 6.2) ..."

# ---- Configuration ----

# ARM64 cross-compiler prefix
CROSS_PREFIX="${CROSS_PREFIX:-aarch64-linux-gnu}"

# Sysroot: root filesystem of the target Jetson
SYSROOT="${SYSROOT:-/opt/jetson-sysroot}"

# Host CUDA toolkit root (must have aarch64 cross-compile packages installed)
CUDA_ROOT="${CUDA_ROOT:-/usr/local/cuda}"

# Staging directory on the host — rsync this to the Jetson after the build
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}/.."
STAGING_DIR="${STAGING_DIR:-${REPO_ROOT}/staging-arm64}"
BUILD_DIR="${REPO_ROOT}/build-arm64"

# ---- Validate toolchain ----

if ! command -v "${CROSS_PREFIX}-gcc" &>/dev/null; then
    echo "ERROR: Cross-compiler ${CROSS_PREFIX}-gcc not found."
    echo "       sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu"
    exit 1
fi

if [ ! -d "${SYSROOT}" ]; then
    echo "ERROR: Sysroot not found at ${SYSROOT}"
    echo "       Set the SYSROOT env var or create the sysroot — see script header."
    exit 1
fi

if [ ! -f "${CUDA_ROOT}/bin/nvcc" ]; then
    echo "ERROR: nvcc not found at ${CUDA_ROOT}/bin/nvcc"
    echo "       Set CUDA_ROOT to your host CUDA toolkit path."
    exit 1
fi

# ---- Generate CMake toolchain file ----

mkdir -p "${BUILD_DIR}"
TOOLCHAIN_FILE="${BUILD_DIR}/toolchain-aarch64-jetson.cmake"

cat > "${TOOLCHAIN_FILE}" << EOF
# CMake toolchain — Jetson Orin Nano (aarch64) + JetPack 6.2
# Generated by jetson_libuvc_crosscompile_installation.sh

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER   ${CROSS_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_PREFIX}-g++)
set(CMAKE_CUDA_COMPILER ${CUDA_ROOT}/bin/nvcc)

set(CMAKE_SYSROOT ${SYSROOT})
set(CMAKE_FIND_ROOT_PATH ${SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Point nvcc at the aarch64 CUDA target libraries
set(CMAKE_CUDA_FLAGS
    "--target-dir ${CUDA_ROOT}/targets/aarch64-linux \
     -ccbin ${CROSS_PREFIX}-g++"
    CACHE STRING "" FORCE)
EOF

echo "Toolchain file written to: ${TOOLCHAIN_FILE}"

# ---- Build ----

cd "${BUILD_DIR}"
echo
echo "Calling cmake (cross-compile)"

cmake "${REPO_ROOT}" \
    -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    -DCMAKE_INSTALL_PREFIX="${STAGING_DIR}" \
    -DFORCE_RSUSB_BACKEND=ON \
    -DBUILD_WITH_CUDA=true \
    -DCMAKE_BUILD_TYPE="${build_type}" \
    -DCMAKE_CUDA_ARCHITECTURES="87"

echo
echo "Running make -j$(nproc)"
make -j"$(nproc)"
echo
echo "Running make install (staging)"
make install

echo
echo "Staged install at: ${STAGING_DIR}"
echo "Deploy to Jetson:"
echo "  rsync -avz ${STAGING_DIR}/ ensio@<jetson-ip>:/home/ensio/evRealSense/"
echo -e "\e[92m\n\e[1mLibrealsense cross-compile completed.\n\e[0m"
